#! /usr/bin/env python
# encoding: utf-8

###############################################################################

def options(opt):
	opt.load('gcc gxx')
	
def configure(cfg):
	cfg.load('gcc gxx')
	
	cfg.env.append_value('CFLAGS', '-std=c99')
	cfg.env.append_value('CXXFLAGS', '-std=c++11')


def build(bld):
	bld.program(
		features = 'cxx',
		includes = '.',
		source = ['max1000_riscv_loader.cpp', 'UART.cpp'],
		target = 'max1000_riscv_loader'
	)

###############################################################################
