#!/bin/bash

# Find waf.
S=`realpath "${BASH_SOURCE[0]}"`
THIS_D=`dirname $S`
D=`dirname $THIS_D`
while true;
do
	FIND_RES=`find -L "$D" -maxdepth 1 -type f -name waf`
	if test "$FIND_RES" != ""
	then
		break
	fi
	
	if test "$D" == "/";
	then
		echo "error: not waf in any parent folder!"
		exit 1
	fi
	
	D=`dirname "$D"`
	#echo $D
done


PYTHONPATH="$D/Common/Scripts/:$PYTHONPATH" COMMON="$D/Common/" "$D/waf" "$@"

exit $?
